In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
resultados=pd.read_csv('resultados_hernia.csv')

In [3]:
resultados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   pelvic_incidence          310 non-null    float64
 1   pelvic_tilt               310 non-null    float64
 2   lumbar_lordosis_angle     310 non-null    float64
 3   sacral_slope              310 non-null    float64
 4   pelvic_radius             310 non-null    float64
 5   degree_spondylolisthesis  310 non-null    float64
 6   class                     310 non-null    object 
dtypes: float64(6), object(1)
memory usage: 17.1+ KB


In [4]:
resultados.head(4)

pelvic_incidence  pelvic_tilt  lumbar_lordosis_angle  sacral_slope  \
0         63.027817    22.552586              39.609117     40.475232   
1         39.056951    10.060991              25.015378     28.995960   
2         68.832021    22.218482              50.092194     46.613539   
3         69.297008    24.652878              44.311238     44.644130   

   pelvic_radius  degree_spondylolisthesis   class  
0      98.672917                 -0.254400  Hernia  
1     114.405425                  4.564259  Hernia  
2     105.985135                 -3.530317  Hernia  
3     101.868495                 11.211523  Hernia

In [5]:
resultados.tail(4)

pelvic_incidence  pelvic_tilt  lumbar_lordosis_angle  sacral_slope  \
306         53.936748    20.721496              29.220534     33.215251   
307         61.446597    22.694968              46.170347     38.751628   
308         45.252792     8.693157              41.583126     36.559635   
309         33.841641     5.073991              36.641233     28.767649   

     pelvic_radius  degree_spondylolisthesis   class  
306     114.365845                 -0.421010  Normal  
307     125.670725                 -2.707880  Normal  
308     118.545842                  0.214750  Normal  
309     123.945244                 -0.199249  Normal

In [6]:
# Codificar las etiquetas de la columna de clase
label_encoder = LabelEncoder()
resultados['class'] = label_encoder.fit_transform(resultados['class'])

# Verifica cómo se codificaron las clases
print(resultados['class'].unique())  # Ejemplo de salida: [0, 1, 2] para 'normal', 'hernia', 'spondilolistesis'

[0 2 1]


In [7]:
X = resultados.drop('class', axis=1)  # Características (todas las columnas menos 'class')
y = resultados['class']  # Etiquetas (la columna 'class')

In [8]:
# Dividir los datos en entrenamiento (80%) y prueba (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=62)


In [9]:
model = RandomForestClassifier(random_state=62)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=62)

In [10]:
y_pred = model.predict(X_test)
print(f"Predicciones: {y_pred}")

Predicciones: [2 0 0 0 2 1 2 1 0 1 0 2 1 2 1 1 1 2 1 0 2 2 1 2 2 2 0 2 0 0 0 2 0 1 2 2 1
 0 2 2 2 1 2 2 1 2 1 2 1 1 0 1 0 2 2 2 0 1 1 1 2 2]


In [11]:
# Precisión
accuracy = accuracy_score(y_test, y_pred)
print(f"Precisión del modelo: {accuracy}")

# Informe de clasificación
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

Precisión del modelo: 0.8064516129032258
                   precision    recall  f1-score   support

           Hernia       0.60      0.69      0.64        13
           Normal       0.75      0.68      0.71        22
Spondylolisthesis       0.96      0.96      0.96        27

         accuracy                           0.81        62
        macro avg       0.77      0.78      0.77        62
     weighted avg       0.81      0.81      0.81        62



In [12]:
# Reemplaza con los valores del nuevo paciente
nuevo_paciente = [[63.027877, 22.552586, 39.609117, 40.475232, 98.672917, -0.2544]]

prediccion_nueva = model.predict(nuevo_paciente)
clase_predicha = label_encoder.inverse_transform(prediccion_nueva)
print(f"La predicción para el nuevo paciente es: {clase_predicha}")

La predicción para el nuevo paciente es: ['Hernia']


C:\Users\Javier\anaconda3\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [13]:
nuevo_paciente = [[75.649731,19.339799,64.148685,56.309932,95.903629,69.551303]]

prediccion_nueva = model.predict(nuevo_paciente)
clase_predicha = label_encoder.inverse_transform(prediccion_nueva)
print(f"La predicción para el nuevo paciente es: {clase_predicha}")

La predicción para el nuevo paciente es: ['Spondylolisthesis']


C:\Users\Javier\anaconda3\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [16]:
print(confusion_matrix(y_test, y_pred))

NameError: name 'confusion_matrix' is not defined

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [15]:
print(confusion_matrix(y_test, y_pred))

[[ 9  4  0]
 [ 6 15  1]
 [ 0  1 26]]


In [16]:
nuevo_paciente = [[74.2541,19.339799,62.148685,56.309932,90.903629,69.551303]]

prediccion_nueva = model.predict(nuevo_paciente)
clase_predicha = label_encoder.inverse_transform(prediccion_nueva)
print(f"La predicción para el nuevo paciente es: {clase_predicha}")

La predicción para el nuevo paciente es: ['Spondylolisthesis']


C:\Users\Javier\anaconda3\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
